# Generated by Django 4.1.5 on 2023-04-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
